%include "json.abnf"

fsm-json = {
  "name" : string,
  "type" : "mealy" | "moore",
  "class" : "static" | "dynamic"
  "apply_event_method" : string
  "initialState" : string,
  "finalState" : string,
  "nodes" : [ node *(, node)]
}

node = {
  "name" : string,
  "type" : "switch" | "state",
  ["transitions" : transition *(, transition)]
}

transition = { 
  "appliedOnEvent" : int,
  ["name" : string,]
  ["setEventId" : int,]
  ["invokeOnTransition" : string,]
  "targetNode" : string
}
