function readAll(file)
    local f = assert(io.open(file, "rb"))
    local content = f:read("*all")
    f:close()
    return content
end
sm = require("sm")
at = sm.new_apptab()
lib = sm.loadlib("/home/anton/lab/sm.exec/v6/test/sm_app/sm_test_apps.so")
noop = sm.lookup(lib, "sm_nope")
at:set(noop, "NOAP")
fsm_str = readAll("test_sm_fsm_1.json")
fsm = sm.new_fsm(fsm_str, at, "moore")
print("FSM:\n")
print(fsm)
