# SM.EXEC
# FSM module unit tests makefile
# anton.bondarenko@gmail.com 

CC		    := gcc
INCLUDE		:= /usr/local/include
SRC			:= ../../src/
OAM			:= ../../oam/
BJHASH		:= ../../lib/bj_hash/



CFLAGS		:= -fPIC -O3 -g -Wall -Werror -I$(INCLUDE)

UFLAGS		:= -g -U__linux__
LIBDIR		:= /usr/local/lib
LFLAGS		:= -L$(LIBDIR)

LIBS		:= -lpthread -ljsmn

.PHONY					:	all
all						:	
							$(CC) $(TFLAGS) \
							$(SRC)sm_sys.c \
							$(SRC)sm_event.c \
							$(SRC)sm_queue.c \
							$(SRC)sm_app.c \
							$(OAM)logger.c \
							sm_test_apps.c \
							$(LFLAGS) \
							$(LIBS)
							
.PHONY					:	clean
clean:						rm -f *.o 

.PHONY					:	rebuild
rebuild:					clean all


#


CC = gcc
INCLUDE = /usr/local/include
SRC = ../../src/
OAM = ../../oam/
BJHASH = ../../lib/bj_hash/
CFLAGS = -fPIC -O3 -g -Wall -Werror
OBJ = $(wildcard *.c)
vpath %.c $(SRC):$(OAM):$(BJHASH)
vpath %.h $(SRC):$(OAM):$(BJHASH):$(INCLUDE)
